[build-system]
requires = ["setuptools>=61.0", "wheel", "pip>=21.0"]
build-backend = "setuptools.build_meta"

[project]
name = "msptools"
version = "0.2.3"
requires-python = ">=3.10"
description = "Tools for Optical Forces Calculation in Multiple Scattering Problems"
authors = [
    { name = "Joan ronquillo", email = "joan.ronquillo@uam.es" }
]
readme = "README.md"
license = { file = "LICENSE" }
dependencies = [
    "numpy",
    "scipy",
    "refractiveindex>=1.0.4"
]

[project.optional-dependencies]
dev = ["pytest"]
docs = ["sphinx"]
gpu = ["cupy"]
plotting = ["matplotlib"]

[tool.setuptools.packages.find]
where = ["src"]

